version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  # pgAdmin Web UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: EMAIL
      PGADMIN_DEFAULT_PASSWORD: CONTRASENA
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  postgres-network:
    driver: bridge